/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#182a21",
        "on-secondary-fixed-variant": "#842502",
        "inverse-primary": "#b7cbbe",
        "outline": "#737874",
        "on-background": "#1b1c18",
        "on-surface": "#1b1c18",
        "on-error-container": "#93000a",
        "secondary": "#a53c19",
        "tertiary-container": "#2e4036",
        "surface-bright": "#fbf9f2",
        "on-primary-fixed-variant": "#394b40",
        "primary-fixed": "#d3e8d9",
        "surface-container": "#f0eee7",
        "secondary-fixed": "#ffdbd0",
        "inverse-on-surface": "#f3f1ea",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2e4036",
        "surface": "#fbf9f2",
        "on-tertiary-fixed-variant": "#394b40",
        "on-primary": "#ffffff",
        "surface-tint": "#506358",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#424844",
        "on-primary-fixed": "#0d1f16",
        "tertiary-fixed-dim": "#b7cbbe",
        "surface-container-highest": "#e4e2dc",
        "on-secondary-container": "#6e1c00",
        "tertiary-fixed": "#d3e8d9",
        "surface-container-high": "#eae8e1",
        "surface-container-low": "#f6f4ec",
        "inverse-surface": "#30312c",
        "background": "#fbf9f2",
        "primary": "#182a21",
        "on-tertiary-fixed": "#0d1f16",
        "on-primary-container": "#97ab9e",
        "primary-fixed-dim": "#b7cbbe",
        "secondary-container": "#ff7e55",
        "on-error": "#ffffff",
        "surface-dim": "#dcdad3",
        "on-tertiary-container": "#97ab9e",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#ffb59f",
        "surface-variant": "#e4e2dc",
        "outline-variant": "#c3c8c2",
        "on-secondary-fixed": "#3a0a00",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["IBM Plex Mono", "monospace"],
        display: ["Cormorant Garamond", "serif"],
      },
    },
  },
  plugins: [],
};
